### Register a user 
POST http://localhost:5003/auth/register 
Content-Type: application/json

{
    "firstname": "jio",
    "lastname" : "calderon",
    "email": "jcalderon@gmail.com",
    "username": "jiocalderon",
    "password": "jiocalderon"
}

# {
#     "username": "jiocalderon",
#     "password": "jiocalderon"
# }

### Login a user POST /AUTH/LOGIN 
POST http://localhost:5003/auth/login
Content-Type: application/json

{
"username": "jiocalderon", "password": "jiocalderon"
}

### Fetch all incidents
GET http://localhost:5003/incident
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzYyOTEyNDI5LCJleHAiOjE3NjI5OTg4Mjl9.-FU1EtN1Qa3IOuCL-ahoo8ZTwj5xh0CY2iONhaAHG-4

### Create an incident
POST http://localhost:5003/incident
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzYyOTEyNDI5LCJleHAiOjE3NjI5OTg4Mjl9.-FU1EtN1Qa3IOuCL-ahoo8ZTwj5xh0CY2iONhaAHG-4

{
    "country": "Philippines",
    "region": "Isabela",
    "city": "Roxas",
    "street": "Nuesa",
    "latitude": "44",
    "longitude": "22",
    "date": "06-11-2025 18:37:10",
    "description": "The bridge is broken"
}

### update an incident
PUT http://localhost:5003/incident/2
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzYyOTEyNDI5LCJleHAiOjE3NjI5OTg4Mjl9.-FU1EtN1Qa3IOuCL-ahoo8ZTwj5xh0CY2iONhaAHG-4

{
    "country": "Philippines",
    "region": "Manila",
    "city": "Quezon City",
    "street": "Esguerra",
    "latitude": "32",
    "longitude": "11",
    "date": "06-12-2025 18:37:10",
    "description": "The road is broken on the right side"
}

### delete an incident
DELETE http://localhost:5003/incident/1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzYyOTEyNDI5LCJleHAiOjE3NjI5OTg4Mjl9.-FU1EtN1Qa3IOuCL-ahoo8ZTwj5xh0CY2iONhaAHG-4
