### Register a user 
POST http://localhost:5003/auth/register 
Content-Type: application/json

{
    "firstname": "jio",
    "lastname" : "calderon",
    "email": "j@bmail.com",
    "username": "gilgamesh@gmail.com",
    "password": "123123123"
}

### Login a user POST /AUTH/LOGIN 
POST http://localhost:5003/auth/login
Content-Type: application/json

{
"username": "gilgamesh@gmail.com", "password": "123123123"
}

### Fetch all incidents
GET http://localhost:5003/incident
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzYyNDg3MjQ2LCJleHAiOjE3NjI1NzM2NDZ9.JSTwSyo9SJ6Dd73m0p_o0DDJpBmbC5_tAC75VUOzats

### Create an incident
POST http://localhost:5003/incident
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzYyNDg3MjQ2LCJleHAiOjE3NjI1NzM2NDZ9.JSTwSyo9SJ6Dd73m0p_o0DDJpBmbC5_tAC75VUOzats

{
    "country": "Philippines",
    "region": "Isabela",
    "city": "Roxas",
    "street": "Nuesa",
    "latitude": "44",
    "longitude": "22",
    "date": "06-11-2025 18:37:10",
    "description": "The bridge is broken"
}