### Register a user 
POST http://localhost:5003/auth/register 
Content-Type: application/json

{
    "firstname": "jio",
    "lastname" : "calderon",
    "email": "j@bmail.com",
    "username": "gilgamesh@gmail.com",
    "password": "123123123"
}

### Login a user POST /AUTH/LOGIN 
POST http://localhost:5003/auth/login Content-Type: application/json

{
"username": "gilgamesh@gmail.com", "password": "123123123"
}